# Indica a PHP dónde están las extensiones de XAMPP
extension_dir = "C:\xampp\php\ext"

# Carga la extensión específica
extension=php_mysqli.dll
extension=mysqli

# Mostrar errores para ayudarte con el TFG
display_errors=On
display_startup_errors=On
error_reporting=E_ALL
# C:\xampp\php\php.exe -S localhost:8000 -c php.ini